// Auto-generated by scripts/gen_types.py — DO NOT EDIT BY HAND.

export interface ExtractConfig {
  /** Input video file or directory of videos. */
  input: string;
  /** Output directory. Sub-folders created per video. */
  output: string;
  /** If True, write all images directly into output/ (filenames stay globally unique). If False, one sub-folder per video. */
  flatten_output: boolean;
  /** Output image format. PNG is lossless; recommended for training. */
  output_format: string;
  /** bucket = resize/crop to the configured training bucket; native = two-stage extraction that filters proxy frames first, then writes winning frames at the source video's original resolution. */
  output_mode: string;
  /** PNG compression level. Every level is lossless; lower values encode faster and create larger files. */
  png_compression: number;
  jpg_quality: number;
  webp_quality: number;
  /** scene = one frame per detected scene; interval = every N seconds; hybrid = scene-based with an upper-bound interval cap. */
  sampling: string;
  /** PySceneDetect ContentDetector threshold. Lower = more scenes. */
  scene_threshold: number;
  /** Candidate frames sampled per scene before quality + dedup. */
  frames_per_scene: number;
  /** Used in interval/hybrid mode as the maximum gap between candidate frames within a single scene. */
  interval_seconds: number;
  /** Min Laplacian variance. Below = blurry, dropped. MMD dance footage often needs 100-200. */
  blur_threshold: number;
  /** Drop frames with mean luma below this (near-black flashes). */
  min_brightness: number;
  /** Drop frames with mean luma above this (near-white flashes). */
  max_brightness: number;
  /** Drop frames with luma std-dev below this (flat colour fields). */
  min_contrast: number;
  /** Auto-detect and crop top/bottom/left/right black bars. */
  detect_letterbox: boolean;
  /** Pixel value below which a row/column is considered 'black'. */
  letterbox_threshold: number;
  /** Fraction of pixels in a row/column that must be below letterbox_threshold for it to count as black. */
  letterbox_min_ratio: number;
  /** Target long-edge resolution (Anima default: 1024). */
  resolution: number;
  /** Min short-edge after bucketing (Anima default: 512). */
  min_bucket: number;
  /** Max long-edge after bucketing (Anima default: 2048). */
  max_bucket: number;
  /** Bucket grid step. Output dims will be multiples of this. Anima default: 64. */
  bucket_step: number;
  /** Reject final crops below this pixel count. Anima auto-drops below 500_000 (0.5 MP); matching that prevents wasted I/O. */
  min_pixels: number;
  /** cover = fill bucket, center-crop excess (Anima style); contain = pad to bucket; longest = scale long edge only, no crop. */
  resize_mode: string;
  /** Enable perceptual-hash deduplication. */
  dedup: boolean;
  /** pHash hash size (8 = 64-bit, default). */
  phash_size: number;
  /** Max Hamming distance to count as duplicate. 0 = identical, 5 ≈ very similar, 10+ = loose. */
  phash_distance: number;
  /** Optional path to persist the global pHash index across runs. */
  dedup_index: string;
  /** standard = streaming pHash/SSIM filters; strong = two-stage proxy clustering before native-resolution output. */
  dedup_mode: string;
  /** Long edge of proxy frames used by strong dedup. CUDA decoding uses scale_cuda when available so full-resolution frames stay on device. */
  dedup_proxy_edge: number;
  /** Maximum interval between proxy candidates during native full-frame scanning. Scene changes are emitted immediately between interval samples. */
  native_scan_interval_seconds: number;
  /** FFmpeg scene-change score used while every source frame is scanned. Lower values emit more short-shot candidates. */
  native_scene_threshold: number;
  /** pHash Hamming distance used as an exact/near-exact strong dedup signal. */
  dedup_phash_distance: number;
  /** Cosine-similarity threshold for strong perceptual fingerprints. Higher values preserve more composition variants. */
  dedup_feature_threshold: number;
  /** Whole-video spatial-feature similarity threshold for quality-first diversity selection. Similar compositions compete even when they occur far apart. 0 disables this additional stage. */
  dedup_content_threshold: number;
  /** SSIM threshold that confirms visually near-identical proxy frames during strong dedup. */
  dedup_strong_ssim_threshold: number;
  /** Temporal neighbourhood used to suppress visually similar frames from the same video. Distinct content inside the window survives. 0 disables temporal suppression. */
  dedup_min_seconds: number;
  /** Feature cosine threshold for near-time diversity suppression. Lower values reject more incremental motion; 1 disables similarity-based temporal suppression. */
  dedup_temporal_feature_threshold: number;
  /** video compares candidates only within one source video; global also removes duplicates across all videos in the run. */
  dedup_scope: string;
  /** Which frame wins a duplicate cluster: the first frame or the sharpest frame by proxy Laplacian score. */
  dedup_keep: string;
  /** Enable SSIM-based diversity filter. Ensures accepted frames within a scene are visually distinct (different poses). */
  ssim_filter: boolean;
  /** Max SSIM between two frames to consider them 'different'. Lower = stricter diversity. 0.85 works well for MMD dance. */
  ssim_threshold: number;
  /** Enable color/lighting diversity filter. Prevents oversampling frames with identical lighting conditions. */
  color_diversity: boolean;
  /** Min chi-squared distance between HSV histograms. Higher = more color variety required. 0.08 works for single-scene MMD. */
  color_distance: number;
  /** Reject frames where the subject is cut off at edges. Useful for character LoRA, less important for style. */
  completeness_filter: boolean;
  /** Min completeness score (0=cut off, 1=fully contained). */
  completeness_threshold: number;
  /** Reject frames where the subject is too small (far away / overhead shots). Safe: auto-disables per video if all frames rejected. */
  subject_size_filter: boolean;
  /** Min foreground-to-frame ratio. 0.15 = subject must occupy at least 15%% of the frame. */
  subject_min_ratio: number;
  /** Minimum images guaranteed per video. If filters are too strict, progressively relaxes them to meet this floor. Capped by max_per_video if set. 0 = no guarantee. */
  min_per_video: number;
  /** Auto-detect blur threshold per video by sampling random frames. Overrides blur_threshold with a data-driven value. */
  auto_quality: boolean;
  /** Keep the top N%% sharpest frames when auto_quality is on. */
  auto_quality_percentile: number;
  /** Calibrate auto-quality independently in fixed timeline windows so a softer section is not rejected by sharper parts of the video. 0 uses one threshold for the whole video. */
  auto_quality_window_seconds: number;
  /** If True, expand the bucket crop to remove peripheral watermarks detected by detect_watermark. Default False (warn-only). Center watermarks are never cropped (would slice the subject). */
  crop_watermark: boolean;
  /** Scan each video for static text/logo overlays (URLs, artist tags, recording-software HUDs). Findings are LOGGED and saved to the per-video stats; the pipeline does NOT crop or modify output bytes. Set False to skip the scan entirely. */
  detect_watermark: boolean;
  /** Experimental: use GPU video decoding (NVDEC/QSV/etc.) if available. Validated against CPU output before use; auto-disabled if results diverge. Saves 2-3x decode time on 4K but has cross-platform reliability risks. */
  gpu_accel: boolean;
  /** 'accurate' = frame-exact seeking (slow but precise); 'keyframe' = snap to nearest I-frame (10-20x faster for 60fps video). */
  decode_mode: string;
  /** Run the WD tagger after extraction and write a .txt caption sidecar next to every image. First enable downloads the model (+ onnxruntime in the .exe) to a per-user cache. */
  tag_images: boolean;
  /** LoRA trigger word. Written as the first caption token in every sidecar. Leave empty for no trigger. */
  trigger_word: string;
  /** WD tagger model (wd-eva02-large-tagger-v3 = most accurate, ~1.2 GB; wd-swinv2-tagger-v3 = lighter, ~450 MB). */
  tagger_model: string;
  /** Minimum confidence for general tags. */
  tag_general_threshold: number;
  /** Minimum confidence for character tags. */
  tag_character_threshold: number;
  /** If >0 (and flatten_output is on), images land in a '<N>_<trigger>' subfolder — the kohya-ss repeats folder convention. */
  kohya_repeats: number;
  /** Comma-separated tags never written into captions (the image itself is kept). Accepts 'long_hair' or 'long hair'. */
  tag_blacklist: string;
  /** Comma-separated tags written right after the trigger word in every caption (e.g. 'anime screencap'). */
  tag_always: string;
  /** If >0, tags present in at least this fraction of tagged images are removed from ALL captions so the trigger word absorbs the constant traits (character-LoRA practice). 0 = off. */
  trait_prune_threshold: number;
  /** Comma-separated tags an image MUST all have; otherwise it is moved to output/_rejected/ (e.g. '1girl'). */
  tag_require: string;
  /** Comma-separated tags; an image having ANY of them is moved to output/_rejected/ (e.g. 'multiple girls, 2boys'). */
  tag_exclude: string;
  /** Per-video time ranges to extract from, in seconds, keyed by video FILENAME: {'dance.mp4': [[30.0, 95.5]]}. Videos without an entry are processed whole. Set from the GUI Advanced window or --segment on the CLI. */
  segments: string;
  /** Generate a contact-sheet PNG overview after extraction. */
  contact_sheet: boolean;
  /** Generate an HTML gallery for visual QA. */
  html_gallery: boolean;
  /** Parallel video workers. 0 = auto-detect based on CPU/RAM. Set explicitly to override (e.g. 1 for low-RAM machines). */
  workers: number;
  /** Use frame-accurate seeking. Slower but avoids keyframe drift. */
  seek_accurate: boolean;
  /** Skip videos whose stats.json already exists (resumable runs). */
  skip_existing: boolean;
  /** Hard cap on output images per video, after all filters. */
  max_per_video: string;
  log_level: string;
}
