"""Generate ui/src/api/types.ts from ExtractConfig's JSON schema.

The Pydantic model is the single source of truth for the config contract; this
script mirrors it into TypeScript so there is no hand-maintained duplicate.
Run: venv/bin/python scripts/gen_types.py
"""

from __future__ import annotations

from pathlib import Path

from vid2dataset.config import ExtractConfig

TS_MAP = {
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "string": "string",
}


def js_type(schema: dict) -> str:
    t = schema.get("type", "string")
    if isinstance(t, list):
        t = "string"  # anyOf null variants collapse to string
    return TS_MAP.get(t, "string")


def main() -> None:
    props = ExtractConfig.model_json_schema()["properties"]
    lines = [
        "// Auto-generated by scripts/gen_types.py — DO NOT EDIT BY HAND.",
        "",
        "export interface ExtractConfig {",
    ]
    for name, schema in props.items():
        desc = schema.get("description")
        if desc:
            lines.append(f"  /** {desc} */")
        lines.append(f"  {name}: {js_type(schema)};")
    lines.append("}")

    out = Path(__file__).resolve().parent.parent / "ui" / "src" / "api" / "types.ts"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({len(props)} fields)")


if __name__ == "__main__":
    main()
